..  |GH|    replace:: *GitHub*
..  _GH:    https://github.com

..  _Git:   https://git-scm.com

..  |IM|    replace:: *iMath*
..  _IM:    https://github.com/rblack42/iMath

..  _Make:  https://www.gnu.org/software/make

..  |PY|    replace:: *Python*
..  _PY:    https://www.python.org/

..  |GUI|                   replace:: *Graphical User Interface*

..  |PyPi|                  replace:: *Python Package Index*
..  _PyPi:                  https://pypi.org/
..  _semantic versioning:   https://semver.org/
..  _Sphinx:                https://www.sphinx-doc.org/en/master/

..  |TDD|                   replace::   *Test Driven Development*
